version: '3.8'

services:
  bigmoon:
    build: .
    container_name: bigmoon
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./app:/app
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped